blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/porifa/laravel-object-blueprint-generator/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/porifa/laravel-object-blueprint-generator/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Request a feature
    url: https://github.com/porifa/laravel-object-blueprint-generator/discussions/new?category=show-and-tell
    about: Show off something you've made using porifa's laravel-object-blueprint-generator
  - name: Report a security issue
    url: https://github.com/porifa/laravel-object-blueprint-generator/security/policy
    about: Learn how to notify us for sensitive bugs
  - name: Report a bug
    url: https://github.com/porifa/laravel-object-blueprint-generator/issues/new
    about: Report a reproducible bug
